- platform: switch
  name: Balcony LED
  entity_id: switch.balcony_led_plug

- platform: group
  name: HA Group Balcony
  entities:
    - light.balcony_window
    - light.balcony_led

- platform: template
  lights:
    ha_template_room_balcony:
      friendly_name: HA Template Room Balcony
      level_template: >
        {{ state_attr("light.ha_group_balcony", "brightness")|int }}
      value_template: >
        {{ is_state("light.ha_group_balcony", "on") }}
      temperature_template: >
        {{
          state_attr("light.ha_group_balcony", "color_temp")|int
          if state_attr("light.ha_group_balcony", "color_temp")|int != 0
          else 153
        }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: balcony_virtual_switch_room_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: balcony_virtual_switch_room_off
      set_level:
        service: custom_event.fire
        data:
          event_type: balcony_set_brightness
          event_data:
            brightness: "{{ brightness }}"
      set_temperature:
        service: custom_event.fire
        data:
          event_type: balcony_set_manual_color
          event_data:
            color: "{{ (153000000 / color_temp)|int }}"

- platform: template
  lights:
    ha_template_individual_balcony_window:
      friendly_name: HA Template Individual Balcony Window
      level_template: >
        {{ state_attr("light.balcony_window", "brightness")|int }}
      value_template: >
        {{ is_state("light.balcony_window", "on") }}
      temperature_template: >
        {{
          state_attr("light.balcony_window", "color_temp")|int
          if state_attr("light.balcony_window", "color_temp")|int != 0
          else 153
        }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: balcony_window_virtual_switch_individual_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: balcony_window_virtual_switch_individual_off
      set_level:
        service: custom_event.fire
        data:
          event_type: ""
      set_temperature:
        service: custom_event.fire
        data:
          event_type: ""

- platform: template
  lights:
    ha_template_individual_balcony_led:
      friendly_name: HA Template Individual Balcony LED
      value_template: >
        {{ is_state("light.balcony_led", "on") }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: balcony_led_virtual_switch_individual_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: balcony_led_virtual_switch_individual_off
