- platform: group
  name: HA Group Bedroom
  entities:
    - light.group_bedroom_adult_top
    - light.group_bedroom_theo_top
    - light.bedroom_bed_led_rgb
    - light.bedroom_wardrobe
    - light.bedroom_table

- platform: mqtt
  schema: json
  name: Group Bedroom Bed
  command_topic: zigbee2mqtt_bedroom/Group Bedroom Bed/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom Bed
  color_mode: true
  brightness: true
  supported_color_modes: ["brightness"]

- platform: mqtt
  schema: json
  name: Group Bedroom Bri
  command_topic: zigbee2mqtt_bedroom/Group Bedroom Bri/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom Bri
  color_mode: true
  brightness: true
  supported_color_modes: ["brightness"]

- platform: mqtt
  schema: json
  name: Group Bedroom Adult Top
  command_topic: zigbee2mqtt_bedroom/Group Bedroom Adult Top/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom Adult Top
  color_mode: true
  brightness: true
  supported_color_modes: ["xy"]

- platform: mqtt
  schema: json
  name: Group Bedroom Theo Top
  command_topic: zigbee2mqtt_bedroom/Group Bedroom Theo Top/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom Theo Top
  color_mode: true
  brightness: true
  supported_color_modes: ["xy"]

- platform: mqtt
  schema: json
  name: Group Bedroom Top
  command_topic: zigbee2mqtt_bedroom/Group Bedroom Top/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom Top
  color_mode: true
  brightness: true
  supported_color_modes: ["xy"]

- platform: mqtt
  schema: json
  name: Group Bedroom Color
  command_topic: zigbee2mqtt_bedroom/Group Bedroom Color/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom Color
  color_mode: true
  brightness: true
  supported_color_modes: ["xy"]

- platform: mqtt
  schema: json
  name: Group Bedroom All
  command_topic: zigbee2mqtt_bedroom/Group Bedroom All/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom All

- platform: mqtt
  schema: json
  name: Group Bedroom All Night
  command_topic: zigbee2mqtt_bedroom/Group Bedroom All Night/set
  state_topic: zigbee2mqtt_bedroom/Group Bedroom All Night

- platform: template
  lights:
    ha_template_room_bedroom:
      friendly_name: HA Template Room Bedroom
      level_template: >
        {{ state_attr("light.ha_group_bedroom", "brightness")|int }}
      value_template: >
        {{ is_state("light.ha_group_bedroom", "on") }}
      color_template: >
        {{ state_attr("light.ha_group_bedroom", "hs_color") if state_attr("light.ha_group_bedroom", "hs_color") else [0,0] }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_virtual_switch_room_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_virtual_switch_room_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_set_brightness
          custom_event_data2: "{{ brightness }}"
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_set_manual_color
          custom_event_data2: "({{ h }},{{ s }})"

- platform: template
  lights:
    ha_template_individual_group_bedroom_adult_top:
      friendly_name: HA Template Individual Group Bedroom Adult Top
      level_template: >
        {{ state_attr("light.group_bedroom_adult_top", "brightness")|int }}
      value_template: >
        {{ is_state("light.group_bedroom_adult_top", "on") }}
      color_template: >
        {{ state_attr("light.group_bedroom_adult_top", "hs_color") if state_attr("light.group_bedroom_adult_top", "hs_color") else [0,0] }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_adult_top_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_adult_top_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: ""

- platform: template
  lights:
    ha_template_individual_group_bedroom_theo_top:
      friendly_name: HA Template Individual Group Bedroom Theo Top
      level_template: >
        {{ state_attr("light.group_bedroom_theo_top", "brightness")|int }}
      value_template: >
        {{ is_state("light.group_bedroom_theo_top", "on") }}
      color_template: >
        {{ state_attr("light.group_bedroom_theo_top", "hs_color") if state_attr("light.group_bedroom_theo_top", "hs_color") else [0,0] }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_theo_top_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_theo_top_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: ""

- platform: template
  lights:
    ha_template_individual_bedroom_bed_led_rgb:
      friendly_name: HA Template Individual Living Room Sofa LED RGB
      level_template: >
        {{ state_attr("light.bedroom_bed_led_rgb", "brightness")|int }}
      value_template: >
        {{ is_state("light.bedroom_bed_led_rgb", "on") }}
      color_template: >
        {{ state_attr("light.bedroom_bed_led_rgb", "hs_color") if state_attr("light.bedroom_bed_led_rgb", "hs_color") else [0,0] }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_bed_led_rgb_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_bed_led_rgb_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: ""


- platform: template
  lights:
    ha_template_individual_bedroom_wardrobe:
      friendly_name: HA Template Individual Bedroom Wardrobe
      level_template: >
        {{ state_attr("light.bedroom_wardrobe", "brightness")|int }}
      value_template: >
        {{ is_state("light.bedroom_wardrobe", "on") }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_wardrobe_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_wardrobe_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""

- platform: template
  lights:
    ha_template_individual_bedroom_table:
      friendly_name: HA Template Individual Bedroom Table
      value_template: >
        {{ is_state("light.bedroom_table", "on") }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_table_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_table_virtual_switch_individual_off

- platform: template
  lights:
    bedroom_table:
      friendly_name: Bedroom Table
      value_template: "off"
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: turn_on_bedroom_table_switch
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: turn_off_bedroom_table_switch
