- platform: group
  name: HA Group Bedroom
  entities:
    - light.group_bedroom_adult_top
    - light.group_bedroom_theo_top
    - light.bedroom_bed_led
    - light.bedroom_wardrobe
    - light.bedroom_table

- platform: template
  lights:
    ha_template_room_bedroom:
      friendly_name: HA Template Room Bedroom
      level_template: >
        {{ state_attr("light.ha_group_bedroom", "brightness")|int }}
      value_template: >
        {{ is_state("light.ha_group_bedroom", "on") }}
      color_template: >
        {{
          state_attr("light.ha_group_bedroom", "hs_color")
          if state_attr("light.ha_group_bedroom", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_virtual_switch_room_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_virtual_switch_room_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_set_brightness
          custom_event_data2: "{{ brightness }}"
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_set_manual_color
          custom_event_data2: "({{ h }},{{ s }})"

- platform: template
  lights:
    ha_template_individual_group_bedroom_adult_top:
      friendly_name: HA Template Individual Group Bedroom Adult Top
      level_template: >
        {{ state_attr("light.group_bedroom_adult_top", "brightness")|int }}
      value_template: >
        {{ is_state("light.group_bedroom_adult_top", "on") }}
      color_template: >
        {{
          state_attr("light.group_bedroom_adult_top", "hs_color")
          if state_attr("light.group_bedroom_adult_top", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_adult_top_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_adult_top_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: ""

- platform: template
  lights:
    ha_template_individual_group_bedroom_theo_top:
      friendly_name: HA Template Individual Group Bedroom Theo Top
      level_template: >
        {{ state_attr("light.group_bedroom_theo_top", "brightness")|int }}
      value_template: >
        {{ is_state("light.group_bedroom_theo_top", "on") }}
      color_template: >
        {{
          state_attr("light.group_bedroom_theo_top", "hs_color")
          if state_attr("light.group_bedroom_theo_top", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_theo_top_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: group_bedroom_theo_top_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: ""

- platform: template
  lights:
    ha_template_individual_bedroom_bed_led:
      friendly_name: HA Template Individual Bedroom Bed LED
      level_template: >
        {{ state_attr("light.bedroom_bed_led", "brightness")|int }}
      value_template: >
        {{ is_state("light.bedroom_bed_led", "on") }}
      color_template: >
        {{
          state_attr("light.bedroom_bed_led", "hs_color")
          if state_attr("light.bedroom_bed_led", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_bed_led_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_bed_led_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""
      set_color:
        service: script.fire_custom_event
        data:
          custom_event_data: ""

- platform: template
  lights:
    ha_template_individual_bedroom_wardrobe:
      friendly_name: HA Template Individual Bedroom Wardrobe
      level_template: >
        {{ state_attr("light.bedroom_wardrobe", "brightness")|int }}
      value_template: >
        {{ is_state("light.bedroom_wardrobe", "on") }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_wardrobe_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_wardrobe_virtual_switch_individual_off
      set_level:
        service: script.fire_custom_event
        data:
          custom_event_data: ""

- platform: template
  lights:
    ha_template_individual_bedroom_table:
      friendly_name: HA Template Individual Bedroom Table
      value_template: >
        {{ is_state("light.bedroom_table", "on") }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_table_virtual_switch_individual_on
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: bedroom_table_virtual_switch_individual_off

- platform: template
  lights:
    bedroom_table:
      friendly_name: Bedroom Table
      value_template: >
        {{ is_state("input_boolean.bedroom_table_lamp", "on") }}
      turn_on:
        service: script.fire_custom_event
        data:
          custom_event_data: turn_on_bedroom_table_switch
      turn_off:
        service: script.fire_custom_event
        data:
          custom_event_data: turn_off_bedroom_table_switch
