# - platform: switch
#   name: Living Room Christmas Tree
#   entity_id: switch.living_room_christmas_tree

- platform: group
  name: HA Group Living Room
  entities:
    - light.group_living_room_top
    - light.living_room_sofa
    - light.living_room_sofa_led
    - light.group_living_room_speakers

- platform: template
  lights:
    ha_template_room_living_room:
      friendly_name: HA Template Room Living Room
      level_template: >
        {{ state_attr("light.ha_group_living_room", "brightness")|int(0) }}
      value_template: >
        {{ is_state("light.ha_group_living_room", "on") }}
      color_template: >
        {{
          state_attr("light.ha_group_living_room", "hs_color")
          if state_attr("light.ha_group_living_room", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: living_room_virtual_switch_room_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: living_room_virtual_switch_room_off
      set_level:
        service: custom_event.fire
        data:
          event_type: living_room_set_brightness
          event_data:
            brightness: "{{ brightness }}"
      set_color:
        service: custom_event.fire
        data:
          event_type: living_room_set_manual_color
          event_data:
            color: "({{ h }},{{ s }})"

- platform: template
  lights:
    ha_template_individual_group_living_room_top:
      friendly_name: HA Template Individual Group Living Room Top
      level_template: >
        {{ state_attr("light.group_living_room_top", "brightness")|int(0) }}
      value_template: >
        {{ is_state("light.group_living_room_top", "on") }}
      color_template: >
        {{
          state_attr("light.group_living_room_top", "hs_color")
          if state_attr("light.group_living_room_top", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: group_living_room_top_virtual_switch_individual_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: group_living_room_top_virtual_switch_individual_off
      set_level:
        service: custom_event.fire
        data:
          event_type: ""
      set_color:
        service: custom_event.fire
        data:
          event_type: ""

- platform: template
  lights:
    ha_template_individual_group_living_room_speakers:
      friendly_name: HA Template Individual Group Living Room Speakers
      level_template: >
        {{ state_attr("light.group_living_room_speakers", "brightness")|int(0) }}
      value_template: >
        {{ is_state("light.group_living_room_speakers", "on") }}
      color_template: >
        {{
          state_attr("light.group_living_room_speakers", "hs_color")
          if state_attr("light.group_living_room_speakers", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: group_living_room_speakers_virtual_switch_individual_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: group_living_room_speakers_virtual_switch_individual_off
      set_level:
        service: custom_event.fire
        data:
          event_type: ""
      set_color:
        service: custom_event.fire
        data:
          event_type: ""

- platform: template
  lights:
    ha_template_individual_living_room_sofa:
      friendly_name: HA Template Individual Living Room Sofa
      level_template: >
        {{ state_attr("light.living_room_sofa", "brightness")|int(0) }}
      value_template: >
        {{ is_state("light.living_room_sofa", "on") }}
      color_template: >
        {{
          state_attr("light.living_room_sofa", "hs_color")
          if state_attr("light.living_room_sofa", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: living_room_sofa_virtual_switch_individual_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: living_room_sofa_virtual_switch_individual_off
      set_level:
        service: custom_event.fire
        data:
          event_type: ""
      set_color:
        service: custom_event.fire
        data:
          event_type: ""

- platform: template
  lights:
    ha_template_individual_living_room_sofa_led:
      friendly_name: HA Template Individual Living Room Sofa LED
      level_template: >
        {{ state_attr("light.living_room_sofa_led", "brightness")|int(0) }}
      value_template: >
        {{ is_state("light.living_room_sofa_led", "on") }}
      color_template: >
        {{
          state_attr("light.living_room_sofa_led", "hs_color")
          if state_attr("light.living_room_sofa_led", "hs_color")
          else [0,0]
        }}
      turn_on:
        service: custom_event.fire
        data:
          event_type: living_room_sofa_led_virtual_switch_individual_on
      turn_off:
        service: custom_event.fire
        data:
          event_type: living_room_sofa_led_virtual_switch_individual_off
      set_level:
        service: custom_event.fire
        data:
          event_type: ""
      set_color:
        service: custom_event.fire
        data:
          event_type: ""
