adaptive_lighting: !include configuration/adaptive_lighting.yaml
api:
automation: !include configuration/automation.yaml
binary_sensor: !include_dir_merge_list configuration/binary_sensor
camera: !include configuration/camera.yaml
default_config:
favicon: !include configuration/favicon.yaml
ffmpeg:
frontend: !include configuration/frontend.yaml
group: !include configuration/group.yaml
homeassistant: !include configuration/homeassistant.yaml
http: !include configuration/http.yaml
image_processing: !include configuration/image_processing.yaml
influxdb: !include configuration/influxdb.yaml
input_boolean: !include_dir_merge_named configuration/input_boolean
input_datetime: !include configuration/input_datetime.yaml
input_number: !include configuration/input_number.yaml
input_select: !include configuration/input_select.yaml
input_text: !include configuration/input_text.yaml
light: !include_dir_merge_list configuration/light
logger: !include configuration/logger.yaml
lovelace: !include configuration/lovelace.yaml
media_player: !include configuration/media_player.yaml
mqtt: !include configuration/mqtt.yaml
notify: !include configuration/notify.yaml
panel_iframe: !include configuration/panel_iframe.yaml
proximity: !include configuration/proximity.yaml
recorder: !include configuration/recorder.yaml
rest_command: !include configuration/rest_command.yaml
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensor
shell_command: !include configuration/shell_command.yaml
system_health:
system_log: !include configuration/system_log.yaml
switch: !include configuration/switch.yaml
telegram_bot: !include configuration/telegram_bot.yaml
timer: !include configuration/timer.yaml
tts: !include configuration/tts.yaml
updater:
utility_meter: !include configuration/utility_meter.yaml
yandex_smart_home: !include configuration/yandex_smart_home.yaml
yandex_station: !include configuration/yandex_station.yaml
zone: !include configuration/zone.yaml
