button_card_templates: !include_dir_merge_named /config/lovelace/templates/buttons
apexcharts_card_templates: !include /config/lovelace/templates/charts/templates.yaml

views:
  - !include /config/lovelace/views/main/home.yaml
  - !include /config/lovelace/views/main/bathroom_entrance.yaml
  - !include /config/lovelace/views/main/living_room.yaml
  - !include /config/lovelace/views/main/kitchen.yaml
  - !include /config/lovelace/views/main/bedroom.yaml
  - !include /config/lovelace/views/main/outside.yaml
  - !include /config/lovelace/views/main/people.yaml

  - !include /config/lovelace/views/settings/settings.yaml
  - !include /config/lovelace/views/settings/entities.yaml
  - !include /config/lovelace/views/settings/sensors.yaml
  - !include /config/lovelace/views/settings/lights.yaml
  - !include /config/lovelace/views/settings/inputs.yaml
  - !include /config/lovelace/views/settings/timers.yaml
  - !include /config/lovelace/views/settings/batteries.yaml
  - !include /config/lovelace/views/settings/system.yaml
  - !include /config/lovelace/views/settings/trackers.yaml
  - !include /config/lovelace/views/settings/appliances.yaml
  - !include /config/lovelace/views/settings/climate.yaml
  - !include /config/lovelace/views/settings/media.yaml
  - !include /config/lovelace/views/settings/consumption.yaml
  - !include /config/lovelace/views/settings/notifications.yaml

# Updated at: 2021-11-09 21:58:34.145316+03:00
