path: settings
title: Settings
icon: mdi:cog
cards:
  - type: vertical-stack
    cards:
      - !include /config/lovelace/elements/navigation.yaml
      - !include /config/lovelace/elements/settings_navigation.yaml
      - type: custom:button-card
        template: header
        name: Updates
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: numeric_label
            name: Core
            entity: input_number.ha_core_updates
            variables:
              entity: input_number.ha_core_updates
              path: /hassio/dashboard
          - type: custom:button-card
            template: numeric_label
            name: Supervisor
            entity: sensor.addons_supervisor_os_updates
            variables:
              entity: sensor.addons_supervisor_os_updates
              path: /hassio/dashboard
          - type: custom:button-card
            template: numeric_label
            name: HACS
            entity: sensor.hacs_updates
            variables:
              entity: sensor.hacs_updates
              path: /hacs
          - type: custom:button-card
            template: numeric_label
            name: Zigbee
            entity: input_number.zigbee_ota_updates
            variables:
              entity: input_number.zigbee_ota_updates
              path: /hassio/ingress/45df7312_zigbee2mqtt
      - type: custom:button-card
        template: header
        name: Attention
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: numeric_label
            name: N/A
            entity: input_number.unavailable_entities
            variables:
              entity: input_number.unavailable_entities
              path: /lovelace/settings_entities
          - type: custom:button-card
            template: numeric_label
            name: Battery
            entity: input_number.low_battery_devices
            variables:
              entity: input_number.low_battery_devices
              path: /lovelace/settings_batteries
          - type: custom:button-card
            template: numeric_label
            name: Logged
            entity: input_number.logged_entities
            variables:
              entity: input_number.logged_entities
              path: /lovelace/settings_logging
          - type: custom:button-card
            template: numeric_label
            name: New
            entity: input_number.new_entities
            variables:
              entity: input_number.new_entities
              path: /lovelace/settings_entities
      - type: custom:button-card
        template: header
        name: Restart
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: restart_system
          entity: input_boolean.ui_running
          name: UI
          icon: mdi:television-guide
          variables:
            name: UI
            short_name: ui
        - type: custom:button-card
          template: restart_system
          entity: input_boolean.ad_running
          name: AD
          icon: mdi:robot
          variables:
            name: AppDaemon
            short_name: ad
        - type: custom:button-card
          template: restart_system
          entity: input_boolean.ha_running
          name: HA
          icon: mdi:home-assistant
          variables:
            name: Home Assistant
            short_name: ha
        - type: custom:button-card
          template: restart_system
          entity: input_boolean.os_running
          name: OS
          icon: mdi:server
          variables:
            name: HassOS
            short_name: os
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: restart_z2m
          triggers_update:
            - binary_sensor.zigbee2mqtt_state
          name: Main
          variables:
            name: Zigbee2mqtt
            addon_item: 45df7312_zigbee2mqtt
            addon_short_name: zigbee2mqtt
        - type: custom:button-card
          template: restart_z2m
          triggers_update:
            - binary_sensor.zigbee2mqtt_entrance_state
          name: Entrance
          variables:
            name: Zigbee2mqtt Entrance
            addon_item: 7c299ebf_zigbee2mqtt_entrance
            addon_short_name: zigbee2mqtt_entrance
        - type: custom:button-card
          template: restart_z2m
          triggers_update:
            - binary_sensor.zigbee2mqtt_bedroom_state
          name: Bedroom
          variables:
            name: Zigbee2mqtt Bedroom
            addon_item: 7c299ebf_zigbee2mqtt_bedroom
            addon_short_name: zigbee2mqtt_bedroom
        - type: custom:button-card
          template: restart_z2m
          triggers_update:
            - binary_sensor.zigbee2mqtt_switches_state
          name: Switches
          variables:
            name: Zigbee2mqtt Switches
            addon_item: 7c299ebf_zigbee2mqtt_switches
            addon_short_name: zigbee2mqtt_switches
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: restart_pi
          triggers_update:
            - sensor.rpi_temp_rpi_living_room
          name: Living Room
          variables:
            name: Raspberry Pi Living Room
            pi_item: living_room
        - type: custom:button-card
          template: restart_pi
          triggers_update:
            - sensor.rpi_temp_rpi_entrance
          name: Entrance
          variables:
            name: Raspberry Pi Entrance
            pi_item: entrance
        - type: custom:button-card
          template: restart_pi
          triggers_update:
            - sensor.rpi_temp_rpi_bedroom
          name: Bedroom
          variables:
            name: Raspberry Pi Bedroom
            pi_item: bedroom
      - !include /config/lovelace/elements/footer.yaml
