path: settings_media
title: Media Settings
icon: mdi:music-circle-outline
cards:
  - type: vertical-stack
    cards:
      - !include /config/lovelace/elements/navigation.yaml
      - !include /config/lovelace/elements/settings_navigation.yaml
      - type: custom:button-card
        template: header
        name: Speakers
      - !include /config/lovelace/elements/bathroom_entrance_sonos.yaml
      - !include /config/lovelace/elements/living_room_sonos.yaml
      - !include /config/lovelace/elements/kitchen_sonos.yaml
      - !include /config/lovelace/elements/bedroom_sonos.yaml
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - entity_id: input_boolean.*_sonos_playing
        sort:
          method: entity_id
      - type: custom:button-card
        template: header
        name: TV
      - type: entities
        entities:
          - switch.living_room_tv_plug
          - input_select.current_universal_tv_source
          - input_boolean.cinema_session
      - type: custom:mini-media-player
        entity: media_player.universal_apple_tv
        artwork: material
        name: Apple TV
        hide:
          icon: true
      - type: custom:mini-media-player
        entity: media_player.universal_playstation_4
        artwork: material
        name: PlayStation 4
        hide:
          icon: true
      - !include /config/lovelace/elements/tv_details.yaml
      - type: custom:button-card
        template: header
        name: Yandex Stations
      - type: entities
        entities:
          - input_select.last_active_yandex_station
          - input_text.active_dialog
          - binary_sensor.living_room_yandex_station_active
          - binary_sensor.bedroom_yandex_station_active
          - type: attribute
            entity: media_player.living_room_yandex_station
            attribute: alice_state
            name: Living Room Alice State
          - type: attribute
            entity: media_player.bedroom_yandex_station
            attribute: alice_state
            name: Bedroom Alice State
          - type: attribute
            entity: media_player.living_room_yandex_station
            attribute: connection_class
            name: Living Room Connection Type
          - type: attribute
            entity: media_player.bedroom_yandex_station
            attribute: connection_class
            name: Bedroom Connection Type
      - type: custom:mini-media-player
        entity: media_player.living_room_yandex_station
        artwork: material
        sound_mode: icon
        hide:
          sound_mode: false
          runtime: false
        tts:
          platform: alice
      - type: custom:mini-media-player
        entity: media_player.bedroom_yandex_station
        artwork: material
        sound_mode: icon
        hide:
          sound_mode: false
          runtime: false
        tts:
          platform: alice
      - !include /config/lovelace/elements/party.yaml
      - type: custom:button-card
        template: header
        name: Other
      - type: entities
        entities:
          - input_boolean.fun_toilet
      - !include /config/lovelace/elements/footer.yaml
