path: settings_appliances
title: Appliances Settings
icon: mdi:washing-machine
cards:
  - type: vertical-stack
    cards:
      - !include /config/lovelace/elements/navigation.yaml
      - !include /config/lovelace/elements/settings_navigation.yaml
      - type: custom:button-card
        template: header
        name: Fridge
      - type: entities
        entities:
          - sensor.kitchen_fridge_temperature
          - sensor.kitchen_freezer_temperature
          - binary_sensor.kitchen_freezer_door
      - type: custom:apexcharts-card
        config_templates: base
        series:
          - entity: sensor.kitchen_fridge_temperature
          - entity: sensor.kitchen_freezer_temperature
      - type: custom:button-card
        template: header
        name: Washing Machine
      - type: entities
        entities:
          - switch.bathroom_washing_machine_plug
          - input_select.washing_machine_status
          - sensor.bathroom_washing_machine_plug_power
          - sensor.washing_machine_plug_median_power
          - sensor.washing_machine_plug_max_power
          - binary_sensor.bathroom_washing_machine_door
        show_header_toggle: false
      - type: history-graph
        hours_to_show: 24
        entities:
          - input_select.washing_machine_status
          - binary_sensor.bathroom_washing_machine_door
      - type: custom:apexcharts-card
        config_templates: base
        series:
          - entity: sensor.bathroom_washing_machine_plug_power
          - entity: sensor.washing_machine_plug_median_power
          - entity: sensor.washing_machine_plug_max_power
      - type: custom:button-card
        template: header
        name: Coffee
      - type: entities
        entities:
          - switch.kitchen_coffee_plug
          - input_boolean.coffee_prepared
          - input_datetime.coffee_turned_on
          - timer.coffee
        show_header_toggle: false
      - type: custom:button-card
        template: header
        name: Cooler
      - type: entities
        entities:
          - switch.kitchen_cooler_plug
      - !include /config/lovelace/elements/footer.yaml
