path: settings_batteries
title: Battery Settings
icon: mdi:battery-outline
cards:
  - type: vertical-stack
    cards:
      - !include /config/lovelace/elements/navigation.yaml
      - !include /config/lovelace/elements/settings_navigation.yaml
      - type: custom:button-card
        template: header
        name: Batteries
      - type: horizontal-stack
        cards:
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
            filter:
              include:
                - entity_id: "sensor.*_battery"
                  options:
                    secondary_info: last-updated
            sort:
              method: state
              numeric: true
      - !include /config/lovelace/elements/footer.yaml
