path: settings_trackers
title: Tracker Settings
icon: mdi:crosshairs-gps
cards:
  - type: vertical-stack
    cards:
      - !include /config/lovelace/elements/navigation.yaml
      - !include /config/lovelace/elements/settings_navigation.yaml
      - type: custom:button-card
        template: header
        name: Guest Mode
      - type: entities
        entities:
          - input_boolean.guest_mode
      - type: custom:button-card
        template: header
        name: Andrey Trackers
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - entity_id: person.andrey
            - entity_id: device_tracker.wifi_andrey*
            - entity_id: device_tracker.bt_andrey*
            - entity_id: device_tracker.bt_*_andrey*
            - entity_id: sensor.bt_andrey*_confidence
            - entity_id: sensor.bt_*_andrey*_confidence
            - entity_id: device_tracker.icloud_andrey*
            - entity_id: device_tracker.ha_andrey*
            - entity_id: input_select.andrey_location
            - entity_id: sensor.andrey_geocoded_location
        sort:
          method: entity_id
      - type: custom:button-card
        template: header
        name: Katya Trackers
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - entity_id: person.katya
            - entity_id: device_tracker.wifi_katya*
            - entity_id: device_tracker.bt_katya*
            - entity_id: device_tracker.bt_*_katya*
            - entity_id: sensor.bt_katya*_confidence
            - entity_id: sensor.bt_*_katya*_confidence
            - entity_id: device_tracker.icloud_katya*
            - entity_id: device_tracker.ha_katya*
            - entity_id: input_select.katya_location
            - entity_id: sensor.katya_geocoded_location
        sort:
          method: entity_id
      - type: custom:button-card
        template: header
        name: Andrey History
      - type: custom:auto-entities
        show_empty: false
        card:
          type: history-graph
        filter:
          include:
            - entity_id: person.andrey
            - entity_id: device_tracker.wifi_andrey*
            - entity_id: device_tracker.bt_andrey*
            - entity_id: device_tracker.bt_*_andrey*
            - entity_id: sensor.bt_andrey*_confidence
            - entity_id: sensor.bt_*_andrey*_confidence
            - entity_id: device_tracker.icloud_andrey*
            - entity_id: device_tracker.ha_andrey*
            - entity_id: input_select.andrey_location
        sort:
          method: entity_id
      - type: custom:button-card
        template: header
        name: Katya History
      - type: custom:auto-entities
        show_empty: false
        card:
          type: history-graph
        filter:
          include:
            - entity_id: person.katya
            - entity_id: device_tracker.wifi_katya*
            - entity_id: device_tracker.bt_katya*
            - entity_id: device_tracker.bt_*_katya*
            - entity_id: sensor.bt_katya*_confidence
            - entity_id: sensor.bt_*_katya*_confidence
            - entity_id: device_tracker.icloud_katya*
            - entity_id: device_tracker.ha_katya*
            - entity_id: input_select.katya_location
      - type: custom:button-card
        template: header
        name: Other Trackers
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - entity_id: device_tracker.*
          exclude:
            - entity_id: device_tracker.wifi_andrey*
            - entity_id: device_tracker.bt_andrey*
            - entity_id: device_tracker.bt_*_andrey*
            - entity_id: device_tracker.icloud_andrey*
            - entity_id: device_tracker.ha_andrey*
            - entity_id: device_tracker.wifi_katya*
            - entity_id: device_tracker.bt_katya*
            - entity_id: device_tracker.bt_*_katya*
            - entity_id: device_tracker.icloud_katya*
            - entity_id: device_tracker.ha_katya*
        sort:
          method: entity_id
      - !include /config/lovelace/elements/footer.yaml
