path: settings_vacuum
title: Vacuum Settings
icon: mdi:robot-vacuum
cards:
  - type: vertical-stack
    cards:
      - !include /config/lovelace/elements/navigation.yaml
      - !include /config/lovelace/elements/settings_navigation.yaml
      - type: custom:button-card
        template: header
        name: Vacuum
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: vacuum_auto
            entity: input_boolean.vacuum_auto_clean
          - type: custom:button-card
            template: base_icon
            entity: vacuum.rockrobo
            icon: mdi:cog
            color: var(--paper-card-background-color)
            tap_action:
              action: navigate
              navigation_path: /roborock_panel
              haptic: success
      - !include /config/lovelace/elements/vacuum.yaml
      - type: history-graph
        hours_to_show: 24
        entities:
          - input_select.vacuum_autoclean_state
          - vacuum.rockrobo
      - !include /config/lovelace/elements/footer.yaml
