- platform: command_line
  name: Katya Home to Work Commute
  command: >
    wget -q --user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36' "https://yandex.ru/maps/213/moscow/?mode=routes&rtext={{states.zone.home.attributes.latitude}}%2C{{states.zone.home.attributes.longitude}}~{{states.zone.adidas.attributes.latitude}}%2C{{states.zone.adidas.attributes.longitude}}&rtt=auto" -O /dev/stdout | sed 's/>/>\n/g' | grep 'class="auto-route-snippet-view__route-title-primary"' -A1 | sed -n 2p | sed 's/<\/div>//g'
  scan_interval: 120
  unit_of_measurement: min
  value_template: >
    {% set hours = 0 %}
    {% set minutes = 0 %}
    {% if "мин" in value and "ч" in value %}
      {% set hours = value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int %}
      {% set minutes = value|regex_findall_index(find="\d+.", index=1, ignorecase=False)|int %}
    {% elif "ч" in value %}
      {% set hours = value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int %}
    {% elif "мин" in value %}
      {% set minutes = value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int %}
    {% else %}
      unavailable
    {% endif %}
    {{ hours * 60 + minutes}}

- platform: command_line
  name: Katya Work to Home Commute
  command: >
    wget -q --user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36' "https://yandex.ru/maps/213/moscow/?mode=routes&rtext={{states.zone.adidas.attributes.latitude}}%2C{{states.zone.adidas.attributes.longitude}}~{{states.zone.home.attributes.latitude}}%2C{{states.zone.home.attributes.longitude}}&rtt=auto" -O /dev/stdout | sed 's/>/>\n/g' | grep 'class="auto-route-snippet-view__route-title-primary"' -A1 | sed -n 2p | sed 's/<\/div>//g'
  scan_interval: 120
  unit_of_measurement: min
  value_template: >
    {% set hours = 0 %}
    {% set minutes = 0 %}
    {% if "мин" in value and "ч" in value %}
      {% set hours = value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int %}
      {% set minutes = value|regex_findall_index(find="\d+.", index=1, ignorecase=False)|int %}
    {% elif "ч" in value %}
      {% set hours = value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int %}
    {% elif "мин" in value %}
      {% set minutes = value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int %}
    {% else %}
      unavailable
    {% endif %}
    {{ hours * 60 + minutes}}
