- platform: template
  sensors:
    price_monthly_water_cold:
      friendly_name: Cold Water Monthly Price
      icon_template: mdi:water-pump
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_monthly_water_cold")|float
          * states("input_number.cold_water_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_daily_water_cold:
      friendly_name: Cold Water Daily Price
      icon_template: mdi:water-pump
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_daily_water_cold")|float
          * states("input_number.cold_water_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_monthly_water_hot:
      friendly_name: Hot Water Monthly Price
      icon_template: mdi:water-pump
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_monthly_water_hot")|float
          * states("input_number.hot_water_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_daily_water_hot:
      friendly_name: Hot Water Daily Price
      icon_template: mdi:water-pump
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_daily_water_hot")|float
          * states("input_number.hot_water_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_monthly_water:
      friendly_name: Water Monthly Price
      icon_template: mdi:water-pump
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_monthly_water_cold")|float * states("input_number.cold_water_tariff")|float
          + states("sensor.meter_monthly_water_hot")|float * states("input_number.hot_water_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_daily_water:
      friendly_name: Water Daily Price
      icon_template: mdi:water-pump
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_daily_water_cold")|float * states("input_number.cold_water_tariff")|float
          + states("sensor.meter_daily_water_hot")|float * states("input_number.hot_water_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_monthly_electricity_t1:
      friendly_name: T1 Electricity Monthly Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_monthly_electricity_t1")|float
          * states("input_number.t1_electricity_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_daily_electricity_t1:
      friendly_name: T1 Electricity Daily Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_daily_electricity_t1")|float
          * states("input_number.t1_electricity_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_monthly_electricity_t2:
      friendly_name: T2 Electricity Monthly Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_monthly_electricity_t2")|float
          * states("input_number.t2_electricity_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_daily_electricity_t2:
      friendly_name: T2 Electricity Daily Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_daily_electricity_t2")|float
          * states("input_number.t2_electricity_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_monthly_electricity_t3:
      friendly_name: T3 Electricity Monthly Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_monthly_electricity_t3")|float
          * states("input_number.t3_electricity_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_daily_electricity_t3:
      friendly_name: T3 Electricity Daily Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (states("sensor.meter_daily_electricity_t3")|float
          * states("input_number.t3_electricity_tariff")|float)|round(2)
        }}

- platform: template
  sensors:
    price_monthly_electricity:
      friendly_name: Electricity Monthly Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (
            states("sensor.meter_monthly_electricity_t1")|float * states("input_number.tariff_electricity_t1")|float
            + states("sensor.meter_monthly_electricity_t2")|float * states("input_number.tariff_electricity_t2")|float
            + states("sensor.meter_monthly_electricity_t3")|float * states("input_number.tariff_electricity_t3")|float
          )|round(2)
        }}

- platform: template
  sensors:
    price_daily_electricity:
      friendly_name: Electricity Daily Price
      icon_template: mdi:flash
      unit_of_measurement: Rub
      value_template: >
        {{
          (
            states("sensor.meter_daily_electricity_t1")|float * states("input_number.tariff_electricity_t1")|float
            + states("sensor.meter_daily_electricity_t2")|float * states("input_number.tariff_electricity_t2")|float
            + states("sensor.meter_daily_electricity_t3")|float * states("input_number.tariff_electricity_t3")|float
          )|round(2)
        }}

- platform: template
  sensors:
    price_monthly_utility:
      friendly_name: Utility Monthly Price
      icon_template: mdi:gauge
      unit_of_measurement: Rub
      value_template: >
        {{ states("sensor.price_monthly_water")|float + states("sensor.price_monthly_electricity")|float }}

- platform: template
  sensors:
    price_daily_utility:
      friendly_name: Utility Daily Price
      icon_template: mdi:gauge
      unit_of_measurement: Rub
      value_template: >
        {{ states("sensor.price_daily_water")|float + states("sensor.price_daily_electricity")|float }}
