- platform: uptime
  name: uptime

- platform: history_stats
  name: Night Scene in Living Zone 12 Hours
  entity_id: input_select.living_scene
  state: night
  type: time
  duration:
    hours: 12
  end: "{{ now() }}"

- platform: history_stats
  name: Night Scene in Living Zone 1 Hour
  entity_id: input_select.living_scene
  state: night
  type: time
  duration:
    hours: 1
  end: "{{ now() }}"

- platform: history_stats
  name: Entrance Door Bell 1 Minute
  entity_id: binary_sensor.entrance_door_bell
  state: "on"
  type: count
  duration:
    minutes: 1
  end: "{{ now() }}"

- platform: statistics
  name: Washing Machine Statistics
  entity_id: sensor.bathroom_washing_machine_plug_power
  sampling_size: 180
  precision: 0
  max_age:
    minutes: 3

- platform: sauresha
  email: !secret sensor_saures_email
  password: !secret sensor_saures_password
  flat_id: !secret sensor_saures_flat_id
  controllers:
    !secret sensor_saures_controller_sn_electricity:
      name: saures_electricity
    !secret sensor_saures_controller_sn_water:
      name: saures_water
  counters:
    !secret sensor_saures_counter_sn_cold:
      name: cold_water
    !secret sensor_saures_counter_sn_hot:
      name: hot_water
    !secret sensor_saures_counter_sn_electricity:
      name: electricity
  scan_interval:
    minutes: 60
