- platform: uptime
  name: uptime

- platform: template
  sensors:
    sun_elevation:
      value_template: >
        {{ state_attr("sun.sun", "elevation") }}
      friendly_name: Sun Elevation

- platform: mqtt
  state_topic: valetudo/rockrobo/state
  json_attributes_topic: valetudo/rockrobo/map_data_parsed
  name: rockrobo_map
  value_template: OK

- platform: template
  sensors:
    circadian_saturation:
      value_template: >
        {% if 100 - (state_attr("switch.adaptive_lighting_default", "sun_position")|float * 100)|int > 100 %}
          100
        {% else %}
          {{ 100 - (state_attr("switch.adaptive_lighting_default", "sun_position")|float * 100)|int }}
        {% endif %}
      friendly_name: Circadian Saturation
      unit_of_measurement: "%"

- platform: history_stats
  name: Night Scene in Living Zone 12 Hours
  entity_id: input_select.living_scene
  state: night
  type: time
  duration:
    hours: 12
  end: "{{ now() }}"

- platform: history_stats
  name: Night Scene in Living Zone 1 Hour
  entity_id: input_select.living_scene
  state: night
  type: time
  duration:
    hours: 1
  end: "{{ now() }}"

- platform: template
  sensors:
    wind_speed:
      value_template: >
        {{ state_attr("weather.home", "wind_speed")|float }}
      friendly_name: Wind Speed
      unit_of_measurement: km/h

- platform: history_stats
  name: Entrance Door Bell 1 Minute
  entity_id: binary_sensor.entrance_door_bell
  state: "on"
  type: count
  duration:
    minutes: 1
  end: "{{ now() }}"
