- platform: uptime
  name: uptime

- platform: template
  sensors:
    sun_elevation:
      value_template: >
        {{ state_attr("sun.sun", "elevation") }}
      friendly_name: Sun Elevation

- platform: mqtt
  state_topic: valetudo/rockrobo/state
  json_attributes_topic: valetudo/rockrobo/map_data_parsed
  name: rockrobo_map
  value_template: OK

- platform: template
  sensors:
    circadian_saturation:
      value_template: >
        {% if 100 - (state_attr("switch.adaptive_lighting_default", "sun_position")|float * 100)|int > 100 %}
          100
        {% else %}
          {{ 100 - (state_attr("switch.adaptive_lighting_default", "sun_position")|float * 100)|int }}
        {% endif %}
      friendly_name: Circadian Saturation
      unit_of_measurement: "%"

- platform: history_stats
  name: Night Scene in Living Zone 12 Hours
  entity_id: input_select.living_scene
  state: night
  type: time
  duration:
    hours: 12
  end: "{{ now() }}"

- platform: history_stats
  name: Night Scene in Living Zone 1 Hour
  entity_id: input_select.living_scene
  state: night
  type: time
  duration:
    hours: 1
  end: "{{ now() }}"

- platform: template
  sensors:
    wind_speed:
      value_template: >
        {{ state_attr("weather.home", "wind_speed")|float }}
      friendly_name: Wind Speed
      unit_of_measurement: "km/h"

- platform: command_line
  name: Andrey Rain
  command: >
    wget -q --user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36' "https://yandex.ru/pogoda/maps/nowcast?lat={{states.device_tracker.ha_andrey_iphone_11_pro_max.attributes.latitude}}&lon={{states.device_tracker.ha_andrey_iphone_11_pro_max.attributes.longitude}}" -O /dev/stdout | sed 's/>/>\n/g' | grep "weather-maps-fact__nowcast-alert" -A1 | tail -1 | sed 's/<\/div>//g' | sed 's|.*\. ||'
  scan_interval: 120

- platform: command_line
  name: Katya Rain
  command: >
    wget -q --user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36' "https://yandex.ru/pogoda/maps/nowcast?lat={{states.device_tracker.ha_katya_iphone_12_pro_max.attributes.latitude}}&lon={{states.device_tracker.ha_katya_iphone_12_pro_max.attributes.longitude}}" -O /dev/stdout | sed 's/>/>\n/g' | grep "weather-maps-fact__nowcast-alert" -A1 | tail -1 | sed 's/<\/div>//g' | sed 's|.*\. ||'
  scan_interval: 120
