- platform: sauresha
  email: !secret sensor_saures_email
  password: !secret sensor_saures_password
  flat_id: !secret sensor_saures_flat_id
  controllers:
    !secret sensor_saures_controller_sn_electricity:
      name: saures_electricity
    !secret sensor_saures_controller_sn_water:
      name: saures_water
  counters:
    !secret sensor_saures_counter_sn_cold:
      name: cold_water
    !secret sensor_saures_counter_sn_hot:
      name: hot_water
    !secret sensor_saures_counter_sn_electricity:
      name: electricity
  scan_interval:
    minutes: 60

- platform: template
  sensors:
    saures_water_counter_battery:
      value_template: >
        {{ state_attr("sensor.sauresha_contr_saures_water", "battery_level") }}
      friendly_name: Saures Water Counter Battery
      unit_of_measurement: "%"
      device_class: battery

- platform: template
  sensors:
    saures_electricity_counter_battery:
      value_template: >
        {{ state_attr("sensor.sauresha_contr_saures_electricity", "battery_level") }}
      friendly_name: Saures Electricity Counter Battery
      unit_of_measurement: "%"
      device_class: battery

- platform: template
  sensors:
    saures_water_cold:
      value_template: >
        {{ states("sensor.sauresha_cold_water") }}
      friendly_name: Saures Cold Water
      unit_of_measurement: m³

- platform: template
  sensors:
    saures_water_hot:
      value_template: >
        {{ states("sensor.sauresha_hot_water") }}
      friendly_name: Saures Hot Water
      unit_of_measurement: m³

- platform: template
  sensors:
    saures_water_total:
      value_template: >
        {{ states("sensor.saures_water_cold")|float + states("sensor.saures_water_hot")|float }}
      friendly_name: Saures Total Water 
      unit_of_measurement: m³

- platform: template
  sensors:
    saures_electricity_t1:
      value_template: >
        {{ state_attr("sensor.sauresha_electricity", "t1") }}
      friendly_name: Saures T1 Electricity
      unit_of_measurement: kWh

- platform: template
  sensors:
    saures_electricity_t2:
      value_template: >
        {{ state_attr("sensor.sauresha_electricity", "t2") }}
      friendly_name: Saures T2 Electricity
      unit_of_measurement: kWh

- platform: template
  sensors:
    saures_electricity_t3:
      value_template: >
        {{ state_attr("sensor.sauresha_electricity", "t3") }}
      friendly_name: Saures T3 Electricity
      unit_of_measurement: kWh

- platform: template
  sensors:
    saures_electricity_total:
      value_template: >
        {{
          states("sensor.saures_electricity_t1")|float
          + states("sensor.saures_electricity_t2")|float
          + states("sensor.saures_electricity_t3")|float
        }}
      friendly_name: Saures Total Electricity
      unit_of_measurement: kWh
