- platform: statistics
  name: Washing Machine Statistics
  entity_id: sensor.bathroom_washing_machine_plug_power
  sampling_size: 180
  precision: 0
  max_age:
    minutes: 3

- platform: template
  sensors:
    washing_machine_plug_median_power:
      value_template: >
        {{ state_attr("sensor.washing_machine_statistics", "median") }}
      friendly_name: Washing Machine Plug Median Power
      unit_of_measurement: W

- platform: template
  sensors:
    washing_machine_plug_max_power:
      value_template: >
        {{ state_attr("sensor.washing_machine_statistics", "max_value") }}
      friendly_name: Washing Machine Plug Max Power
      unit_of_measurement: W
