- platform: mqtt
  name: Bedroom Window Position
  state_topic: bedroom_window/CurrentPosition
  unit_of_measurement: "%"
  icon: mdi:window-open-variant

- platform: mqtt
  name: Kitchen Window Position
  state_topic: kitchen_window/CurrentPosition
  unit_of_measurement: "%"
  icon: mdi:window-open-variant
