base:
  styles:
    card:
      - height: 72px

base_icon:
  template: base
  show_label: false
  show_name: false
  color: auto
  color_type: card

base_label:
  template: base
  show_label: true
  show_icon: false
  show_state: false

numeric_label:
  template: base_label
  color: auto
  color_type: card
  state:
    - value: 0
      operator: "!="
      color: var(--paper-item-icon-active-color)
    - operator: default
      color: var(--paper-card-background-color)
  label: >
    [[[ return parseInt(states[variables.entity].state, 0).toString(); ]]]
  tap_action:
    action: navigate
    navigation_path: >
      [[[ return variables.path; ]]]
    haptic: success
  variables:
    entity: ""
    path: ""
