- platform: mqtt
  name: Zigbee2mqtt Kitchen State
  state_topic: zigbee2mqtt_kitchen/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Entrance State
  state_topic: zigbee2mqtt_entrance/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Bedroom State
  state_topic: zigbee2mqtt_bedroom/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Living Room State
  state_topic: zigbee2mqtt_living_room/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Entrance Door Bell
  state_topic: zigbee2mqtt_entrance/Entrance Door Bell
  value_template: >
    {% if value_json.action in ["single", "hold"] %}
      ON
    {% else %}
      OFF
    {% endif %}

- platform: mqtt
  name: Entrance Door Camera Motion
  state_topic: entrance_camera/motion
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

- platform: mqtt
  name: Kitchen Window Active
  state_topic: kitchen_window/State
  value_template: >
    {% if value in ["INCREASING", "DECREASING"] %}
      ON
    {% else %}
      OFF
    {% endif %}
  icon: mdi:window-closed-variant

- platform: mqtt
  name: Bedroom Window Active
  state_topic: bedroom_window/State
  value_template: >
    {% if value in ["INCREASING", "DECREASING"] %}
      ON
    {% else %}
      OFF
    {% endif %}
  icon: mdi:window-closed-variant
