- platform: mqtt
  name: Zigbee2mqtt State
  state_topic: zigbee2mqtt/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Entrance State
  state_topic: zigbee2mqtt_entrance/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Bedroom State
  state_topic: zigbee2mqtt_bedroom/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Switches State
  state_topic: zigbee2mqtt_switches/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Entrance Door Bell
  state_topic: zigbee2mqtt_entrance/Entrance Door Bell
  value_template: >
    {% if value_json.action in ["single", "hold"] %}
      ON
    {% else %}
      OFF
    {% endif %}

- platform: mqtt
  name: Entrance Door Camera Motion
  state_topic: entrance_camera/motion
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
