- platform: doods
  url: !secret image_processing_doods_host
  detector: default
  # scan_interval: 5
  source:
    - entity_id: camera.living_room_camera
  # file_out:
  #   - /config/www/person.jpg
  labels:
    - name: person
      confidence: 50
