- platform: universal
  name: Universal Apple TV
  children:
    - media_player.living_room_apple_tv
  state_template: >
    {% if is_state("binary_sensor.living_room_tv", "off") %}
      off
    {% else %}
      {{ states("media_player.living_room_apple_tv") }}
    {% endif %}
  attributes:
    volume_level: media_player.living_room_sonos|volume_level
    is_volume_muted: media_player.living_room_sonos|is_volume_muted
  commands:
    turn_on:
      service: script.turn_on
      data:
        entity_id: script.tv_turn_on
    turn_off:
      service: script.turn_on
      data:
        entity_id: script.tv_turn_off
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.living_room_sonos
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.living_room_sonos
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.living_room_sonos
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_sonos
        volume_level: "{{ volume_level }}"

- platform: universal
  name: Universal Playstation 4
  children:
    - media_player.playstation_4
  state_template: >
    {% if is_state("binary_sensor.living_room_tv", "off") %}
      off
    {% else %}
      {{ states("media_player.playstation_4") }}
    {% endif %}
  attributes:
    volume_level: media_player.living_room_sonos|volume_level
    is_volume_muted: media_player.living_room_sonos|is_volume_muted
  commands:
    turn_on:
      service: script.turn_on
      data:
        entity_id: script.playstation_4_turn_on
    turn_off:
      service: script.turn_on
      data:
        entity_id: script.tv_turn_off
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.living_room_sonos
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.living_room_sonos
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.living_room_sonos
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_sonos
        volume_level: "{{ volume_level }}"
