- platform: template
  switches:
    ac:
      friendly_name: AC
      value_template: >
        {% if is_state("binary_sensor.living_room_ac_door", "off") %}
          off
        {% else %}
          on
        {% endif %}
      turn_on:
        service: script.fire_custom_event
        data_template:
          custom_event_data: manual_ac_on
      turn_off:
        service: script.fire_custom_event
        data_template:
          custom_event_data: manual_ac_off
