- platform: template
  switches:
    ac:
      friendly_name: AC
      value_template: >
        {% if is_state("binary_sensor.living_room_ac_door", "off") %}
          off
        {% else %}
          on
        {% endif %}
      turn_on:
        service: custom_event.fire
        data_template:
          event_type: manual_ac_on
      turn_off:
        service: custom_event.fire
        data_template:
          event_type: manual_ac_off
