substitutions:
  hostname: bathroom_freshener
  name: Bathroom Freshener

esphome:
  name: $hostname
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  use_address: 192.168.1.245
  fast_connect: true
  ap:
    ssid: $hostname
    password: ""

logger:

api:

ota:

switch:
  - platform: gpio
    name: Bathroom Freshener
    pin:
      number: D2
    id: bathroom_freshener
    inverted: yes
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: bathroom_freshener
      - number.set:
          id: freshener_counter
          value: !lambda |-
            return ((id(freshener_counter).state)+1);
      - component.update: freshener_counter 
  - platform: template
    name: Reset Freshener Counter
    id: reset_freshener_counter
    turn_on_action:
      - number.set:
          id: freshener_counter
          value: 0
      - component.update: freshener_counter 

number:
  - platform: template
    name: Freshener Counter
    id: freshener_counter
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 1000
    step: 1
    optimistic: true
