substitutions:
  hostname: bathroom-freshener
  name: Bathroom Freshener
  ip: 192.168.1.245

esphome:
  name: $hostname
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: true
  on_boot:
    priority: -100
    then:
      - wait_until:
          time.has_time:
      - delay: 1s
      - sensor.template.publish:
          id: uptime
          state: !lambda "return id(sntp_time).now().timestamp;"

time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-3

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  use_address: $ip
  fast_connect: true
  ap:
    ssid: $hostname
    password: ""

logger:

api:

ota:

sensor:
  - platform: template
    name: $name Uptime
    update_interval: never
    device_class: timestamp
    id: uptime

switch:
  - platform: gpio
    name: Bathroom Freshener
    pin:
      number: D2
    id: bathroom_freshener
    inverted: yes
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: bathroom_freshener
      - number.set:
          id: freshener_counter
          value: !lambda |-
            return ((id(freshener_counter).state)+1);
      - component.update: freshener_counter 
  - platform: template
    name: Reset Freshener Counter
    id: reset_freshener_counter
    turn_on_action:
      - number.set:
          id: freshener_counter
          value: 0
      - component.update: freshener_counter 

number:
  - platform: template
    name: Freshener Counter
    id: freshener_counter
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 1000
    step: 1
    optimistic: true
