substitutions:
  hostname: bathroom-toilet-occupancy
  name: Bathroom Toilet Occupancy
  ip: 192.168.1.123

esphome:
  name: $hostname
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    priority: -100
    then:
      - wait_until:
          time.has_time:
      - delay: 1s
      - sensor.template.publish:
          id: uptime
          state: !lambda "return id(sntp_time).now().timestamp;"

time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-3

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  use_address: $ip
  fast_connect: true
  ap:
    ssid: $hostname
    password: ""

logger:

api:

ota:

sensor:
  - platform: template
    name: $name Uptime
    update_interval: never
    device_class: timestamp
    id: uptime
  - platform: ultrasonic
    id: ultrasonic_sensor
    trigger_pin: D1
    echo_pin: D2
    update_interval: 1s
    filters:
      - filter_out: nan
      - sliding_window_moving_average:
          window_size: 4
          send_every: 4

binary_sensor:
  - platform: template
    name: Bathroom Toilet Occupancy
    id: bathroom_toilet_occupancy
    device_class: occupancy
    lambda: |-
      if (
        id(ultrasonic_sensor).state > 0.01
        and id(ultrasonic_sensor).state < 0.3
      ) {
        return true;
      } else {
        return false;
      }
