substitutions:
  hostname: bedroom-theo-bed-occupancy
  name: Bedroom Theo Bed Occupancy

esphome:
  name: $hostname
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  use_address: 192.168.1.75
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: $hostname
    password: ""

logger:

api:

ota:

sensor:
  - platform: adc
    name: Bedroom Theo Bed Top Sensor
    pin: GPIO34
    id: bedroom_theo_bed_top_sensor
    unit_of_measurement: "%"
    device_class: ""
    state_class: ""
    update_interval: 0.1s
    attenuation: 11db
    filters:
      - lambda: return abs(100 - (x / 3.9 * 100));
      - median:
          window_size: 20
          send_every: 20
          send_first_at: 20

  - platform: adc
    name: Bedroom Theo Bed Bottom Sensor
    pin: GPIO35
    id: bedroom_theo_bed_bottom_sensor
    unit_of_measurement: "%"
    device_class: ""
    state_class: ""
    update_interval: 0.1s
    attenuation: 11db
    filters:
      - lambda: return abs(100 - (x / 3.9 * 100));
      - median:
          window_size: 20
          send_every: 20
          send_first_at: 20

binary_sensor:
  - platform: template
    name: Bedroom Theo Bed Occupancy
    id: bedroom_theo_bed_occupancy
    device_class: occupancy
    lambda: |-
      if (
        id(bedroom_theo_bed_top_sensor).state > 20
        or id(bedroom_theo_bed_bottom_sensor).state > 20
        or (
          id(bedroom_theo_bed_top_sensor).state
          + id(bedroom_theo_bed_bottom_sensor).state
        ) > 30
      ) {
        return true;
      } else {
        return false;
      }
