substitutions:
  hostname: bedroom_bed_occupancy
  name: Bedroom Bed Occupancy

esphome:
  name: $hostname
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  use_address: 192.168.1.98
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: $hostname
    password: ""

logger:

api:

ota:

sensor:
  - platform: adc
    pin: GPIO35
    id: left_top_sensor
    update_interval: 1s
    attenuation: 11db

  - platform: adc
    pin: GPIO34
    id: right_top_sensor
    update_interval: 1s
    attenuation: 11db

  - platform: adc
    pin: GPIO33
    id: left_bottom_sensor
    update_interval: 1s
    attenuation: 11db

  - platform: adc
    pin: GPIO32
    id: right_bottom_sensor
    update_interval: 1s
    attenuation: 11db

binary_sensor:
  - platform: template
    name: $name Left Person
    id: left_person
    lambda: |-
      if (id(left_top_sensor).state <= 3 or id(left_bottom_sensor).state <= 3) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_off: 5s

  - platform: template
    name: $name Right Person
    id: right_person
    lambda: |-
      if (id(right_top_sensor).state <= 3 or id(right_bottom_sensor).state <= 3) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_off: 5s

  - platform: template
    name: $name
    id: any
    lambda: |-
      if (id(left_person).state ||
          id(right_person).state) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_off: 10s
