substitutions:
  hostname: bedroom-theo-sonoff-mini
  name: Bedroom Theo Sonoff Mini
  ip: 192.168.1.160

esphome:
  name: $hostname
  platform: ESP8266
  board: esp8285
  on_boot:
    priority: -100
    then:
      - wait_until:
          time.has_time:
      - delay: 1s
      - sensor.template.publish:
          id: uptime
          state: !lambda "return id(sntp_time).now().timestamp;"

time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-3

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  use_address: $ip
  fast_connect: true
  ap:
    ssid: $hostname
    password: ""

logger:

api:

ota:

sensor:
  - platform: template
    name: $name Uptime
    update_interval: never
    device_class: timestamp
    id: uptime

web_server:

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: 
          id: relay_01

switch:
  - platform: gpio
    name: $name
    icon: "mdi:electric-switch"
    pin: GPIO12
    id: relay_01
    restore_mode: restore_default_on