substitutions:
  hostname: bedroom-scales
  name: Bedroom Scales

esphome:
  name: $hostname
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  use_address: 192.168.1.135
  fast_connect: true
  ap:
    ssid: $hostname
    password: ""

logger:

api:

ota:

esp32_ble_tracker:

sensor:
  - platform: xiaomi_miscale
    mac_address: "70:87:9E:24:92:D6"
    weight:
      id: weight_miscale
      name: Bedroom Scales
      on_value:
        - homeassistant.event:
            event: esphome.weight
            data:
              weight: !lambda |-
                return id(weight_miscale).state;
