- platform: mqtt
  name: Zigbee2mqtt State
  state_topic: zigbee2mqtt/bridge/state
  payload_on: online
  payload_off: offline

- platform: mqtt
  name: Zigbee2mqtt Entrance State
  state_topic: zigbee2mqtt_entrance/bridge/state
  payload_on: online
  payload_off: offline

- platform: mqtt
  name: Zigbee2mqtt Bedroom State
  state_topic: zigbee2mqtt_bedroom/bridge/state
  payload_on: online
  payload_off: offline

- platform: mqtt
  name: Zigbee2mqtt Switches State
  state_topic: zigbee2mqtt_switches/bridge/state
  payload_on: online
  payload_off: offline
