- platform: mqtt
  name: Entrance Door Bell
  state_topic: zigbee2mqtt_entrance/Entrance Door Bell
  value_template: >
    {% if value_json.action in ["single", "hold"] %}
      ON
    {% else %}
      OFF
    {% endif %}

- platform: mqtt
  name: Entrance Door Camera Motion
  state_topic: entrance_camera/motion
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
