- platform: ping
  host: 8.8.8.8
  count: 2
  scan_interval: 30
  name: Google Connectivity

- platform: ping
  host: 1.1.1.1
  count: 2
  scan_interval: 30
  name: Cloudflare Connectivity

- platform: ping
  host: 77.88.8.8
  count: 2
  scan_interval: 30
  name: Yandex Connectivity

- platform: ping
  host: 192.168.1.1
  count: 2
  scan_interval: 30
  name: Router Connectivity
