- platform: mqtt
  name: Zigbee2mqtt Kitchen State
  state_topic: zigbee2mqtt_kitchen/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Entrance State
  state_topic: zigbee2mqtt_entrance/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Bedroom State
  state_topic: zigbee2mqtt_bedroom/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee

- platform: mqtt
  name: Zigbee2mqtt Living Room State
  state_topic: zigbee2mqtt_living_room/bridge/state
  payload_on: online
  payload_off: offline
  icon: mdi:zigbee
